spring:
  application:
    name: disturbances
  config:
    import: "configserver:"
  cloud:
    config:
      uri: http://localhost:8081
  pid:
    fail-on-write-error: true
    file: pid/disturbances.pid
management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    git:
      enabled: true
      mode: full
info:
  app:
    name: Disturbances
    version: ${project.version}
server:
  port: 8087
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
  instance:
    prefer-ip-address: true