spring:
  cloud:
    gateway:
      routes:
        - id: all-stations
          uri: lb://station-registry
          predicates:
            - Path=/api/v1/station
            - Method=GET
          filters:
            - RewritePath=/api/v1/station, /
        - id: nearby-stations
          uri: lb://station-registry
          predicates:
            - Path=/api/v1/station/nearby
            - Method=GET
          filters:
            - RewritePath=/api/v1/station/nearby, /nearby
        - id: departures
          uri: lb://timetable
          predicates:
            - Path=/api/v1/station/*/departures
            - Method=GET
          filters:
            - RewritePath=/api/v1/station/(?<id>/?.*)/departures, /departures?code=$\{id}
        - id: arrivals
          uri: lb://timetable
          predicates:
            - Path=/api/v1/station/*/arrivals
            - Method=GET
          filters:
            - RewritePath=/api/v1/station/(?<id>/?.*)/arrivals, /arrivals?code=$\{id}
        - id: notifications
          uri: lb://disruptions
          predicates:
            - Path=/api/v1/notification
            - Method=GET
          filters:
            - RewritePath=/api/v1/notification, /notification
        - id: disturbances
          uri: lb://disruptions
          predicates:
            - Path=/api/v1/disturbance
            - Method=GET
          filters:
            - RewritePath=/api/v1/disturbance, /disturbance
application:
  security:
    user: ns-demo
    password: password
    roles: API-USER