application:
  ns-api:
    base-url: https://gateway.apiportal.ns.nl
    public-travel-info:
      base-path: /public-reisinformatie/api/v2
      api-key:
        header: Ocp-Apim-Subscription-Key
        value: d959172d861e499aae8849de1bb26f4c