spring:
  application:
    name: config-server
  profiles:
    active: native
  pid:
    fail-on-write-error: true
    file: pid/config-server.pid
  cloud:
    config:
      server:
        native:
          search-locations: configs
server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
  instance:
    prefer-ip-address: true